# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG JUPYTERHUB_VERSION
FROM jupyterhub/jupyterhub-onbuild:$JUPYTERHUB_VERSION

# Install dockerspawner, oauth
RUN /opt/conda/bin/pip install --no-cache-dir \
        oauthenticator==0.7.* \
        dockerspawner==0.9.*

COPY ./userlist /srv/jupyterhub/userlist
